#!/usr/bin/env bash

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
  CACHE="~/.cache/ms-playwright"
elif [[ "$OSTYPE" == "cygwin" ]]; then
  CACHE="~/.cache/ms-playwright"
elif [[ "$OSTYPE" == "freebsd"* ]]; then
  CACHE="~/.cache/ms-playwright"
elif [[ "$OSTYPE" == "darwin"* ]]; then
  CACHE="~/Library/Caches/ms-playwright"
else
  CACHE="%USERPROFILE%\AppData\Local\ms-playwright"
fi

if [[ -z "$(ls $CACHE 2>&1  | grep chromium)" ]]; then
  echo "Installing Playwright browsers..."
  npx playwright install --with-deps chromium "$@"
else
  echo "Playwright browsers already cached, skipping installation"
fi

if [[ -z $(node -pe 'require.resolve("@diplodoc/cli")') ]]; then
  npm i @diplodoc/cli@latest --no-save
fi